#
# ConversePlugin Configuration File
#

# URL where players should appeal their bans
banurl: https://unraveledmc.com/appeal

# What mode is the server in?
mode: default

# What commands should be blocked when a player is muted?
muted_commands:
  - msg
  - reply
  - tell
  - me
  - mail

# Permissions Configuration
permissions:
  # What is the OP group name?
  op: default

  # What is the Mod group name?
  mod: mod

  # What is the Senior Mod group name?
  senior_mod: seniormod

  # What is the Developer group name?
  developer: developer

  # What is the Executive group name?
  executive: executive

  # What is the Architect group name?
  architect: architect

# Tab list settings
tablist:
  # What should the header be?
  header:
    - "&7Unraveled&8MC"
    - "&8--+--"

  # What should the footer be?
  footer:
    - "&8--+--"
    - "&7unraveledmc.com"
    - "&7discord.gg/Wab3tFq"

#Configuration Settings!
config:
  item_drops: false
  fluid_place: false
  fire_place: false
  secret: false