name: ${project.name}
version: ${project.version}
description: Plugin for UnraveledMC
author: UnraveledMC
main: net.novelmc.Converse
depend: [LuckPerms]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other staff members
    aliases: [ac, o]
  ban:
    usage: /<command> <player> <duration> [reason]
    description: Temporarily bans a player
    aliases: [eban, banip, ebanip, tempban, etempban]
  banlookup:
    usage: /<command> <player>
    description: Look up a player ban
    aliases: [bl]
  blackchat:
    usage: /<command> <player>
    description: Makes a players chat messages show up in black
    aliases: [darkchat, graychat]
  coins:
    usage: /<command>
    description: Check your coin balance.
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
  dban:
    usage: /<command> <player> [reason]
    description: Bans a player for a day
    aliases: [dayban, gtfo]
  enderworld:
    usage: /<command>
    description: Teleport to the enderworld
    aliases: [ew]
  flatworld:
    usage: /<command>
    description: Teleport to the flatworld
    aliases: [flatlands, fw]
  manageshop:
    usage: /<command> <add | del | set | get> <player> [amount]
    description: Manages the shop for staff members
    aliases: [mshop, shopadmin]
  mode:
    usage: /<command> [event | dev | staff | off]
    description: Change the server mode
  mute:
    usage: /<command> <player | purge>
    description: Mute a player or purge all mutes
    aliases: [stfu, emute]
  netherworld:
    usage: /<command>
    description: Teleport to the netherworld
    aliases: [nw]
  overworld:
    usage: /<command>
    description: Teleport to the overworld
    aliases: [ow]
  orbit:
    usage: /<command> <player> <on | off>
    description: Toggles a player's orbited state
  permban:
    usage: /<command> <player> [reason]
    description: Permanently bans a player
  plotworld:
    usage: /<command>
    description: Teleport to the plotworld
  say:
    usage: /<command> <msg>
    description: Moderator announcements
    aliases: [shout, announce, broadcast]
  shop:
    usage: /<command>
    description: Opens the shop menu.
    aliases: [umcshop]
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage staff members
    aliases: [saconfig]
  staffworld:
    usage: /<command> <add <player> | remove <player>>
    description: Teleport to the staffworld
    aliases: [adminworld, aw, sw]
  unban:
    usage: /<command> <player>
    description: Unbans a banned player.
    aliases: [pardon, epardon, unpermban]
  unloadchunks:
    usage: /<command>
    description: Unloads all unused chunks
    aliases: [uc]
  voterworld:
    usage: /<command>
    description: Teleport to the voterworld
    aliases: [vw]
  cage:
    usage: /<command> <<player> [block] | purge>
    description: Create a cage around a player
  playtime:
    usage: /<command> [player]
    description: View player playtime
